#define HSV_DIM 0, 0, 10
#define HSV_GOLD_ORANGE 240, 255, 127
#define HSV_GOLD_ORANGE_DIM 240, 255, 63
#define HSV_CUSTOM_GREEN 120, 255, 85
#define HSV_CUSTOM_PURPLE 280, 255, 255
#define HSV_CUSTOM_PURPLE_DIM 280, 255, 127
#define HSV_CUSTOM_BLUE 240, 255, 127
#define HSV_CUSTOM_BLUE_DIM 240, 255, 63
#define HSV_CUSTOM_RED 0, 255, 170

#define HSV_COLOR_DEFAULT    HSV_CUSTOM_PURPLE_DIM
#define HSV_COLOR_GAME       HSV_CUSTOM_PURPLE
#define HSV_COLOR_NAVIGATION HSV_CUSTOM_BLUE_DIM
#define HSV_COLOR_NUMERAL    HSV_GOLD_ORANGE_DIM
#define HSV_COLOR_SYMBOLS    HSV_GOLD_ORANGE
#define HSV_COLOR_POINTER    HSV_CUSTOM_BLUE
#define HSV_COLOR_FUNCTION   HSV_CUSTOM_GREEN
#define HSV_COLOR_OSL        HSV_CUSTOM_RED
